parameters:
#    tracker_affiliate_network.example.class: Tracker\AffiliateNetworkBundle\Example

services:
#    tracker_affiliate_network.example:
#        class: %tracker_affiliate_network.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
