<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120418131116 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE trafficsource ADD serviceAuthenticationMethod VARCHAR(255) DEFAULT 'username_password' NOT NULL");
        $this->addSql("ALTER TABLE trafficsource ADD serviceApiKey VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE trafficsource ADD serviceUsername VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE trafficsource ADD servicePassword VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE campaign ALTER creativeidentifiers TYPE TEXT");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE TrafficSource DROP serviceAuthenticationMethod");
        $this->addSql("ALTER TABLE TrafficSource DROP serviceApiKey");
        $this->addSql("ALTER TABLE TrafficSource DROP serviceUsername");
        $this->addSql("ALTER TABLE TrafficSource DROP servicePassword");
        $this->addSql("ALTER TABLE Campaign ALTER creativeIdentifiers TYPE TEXT");
    }
}
