parameters:
#    tracker_stats.example.class: Tracker\StatsBundle\Example

services:
#    tracker_stats.example:
#        class: %tracker_stats.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
