parameters:
#    tracker_account_manager.example.class: Tracker\AccountManagerBundle\Example

services:
#    tracker_account_manager.example:
#        class: %tracker_account_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
